install mysql

diff --git a/09-install-mysql b/09-install-mysql
--- a/09-install-mysql
+++ b/09-install-mysql
@@ -10,4 +10,12 @@ else
 echo "you are root user"
 fi
 
-echo "print"
+yum install mysql -y
+
+if ( $? -ne 0 )
+then
+echo "ERROR : installing mysql is failed"
+exit 1
+else
+echo "installing mysql is success"
+fi
