install git

diff --git a/09-install-mysql b/09-install-mysql
--- a/09-install-mysql
+++ b/09-install-mysql
@@ -21,3 +21,11 @@ echo "installing mysql is success"
 fi
 
 yum install git -y
+
+if [ $? -ne 0 ]
+then
+echo "ERROR : installing git is failed"
+exit 1
+else
+echo "installing git is success"
+fi
